CREATE TABLE ACCOUNT (
	ACCOUNT_ID BIGINT PRIMARY KEY NOT NULL, 
	BANK_NAME VARCHAR(45), 
	TYPE VARCHAR(45), 
	ACCOUNT_NAME VARCHAR(45), 
	ACCOUNT_NUMBER VARCHAR(45), 
	IFSC_CODE VARCHAR(45), 
	MICR VARCHAR(45), 
	BRANCH_NAME VARCHAR(45), 
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	
CREATE TABLE ADDRESS (
	ADDRESS_ID BIGINT PRIMARY KEY NOT NULL, 
	STREET VARCHAR(45), 
	STATE_ID BIGINT, 
	CITY_ID BIGINT, 
	PIN_CODE VARCHAR(45), 
	CREATED_DTTM TIMESTAMP,
	MODIFIED_DTTM TIMESTAMP
);
ALTER TABLE ADDRESS ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW();

ALTER TABLE ADDRESS ALTER COLUMN CREATED_DTTM SET DEFAULT NOW();
CREATE TABLE CATEGORY  (
	CATEGORY_ID BIGINT PRIMARY KEY,
	IMAGE_LOCATION VARCHAR(45),
	CATEGORY_COLUMN BIGINT,
	PARENT_ID BIGINT,
	SORT_ORDER SMALLINT,
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);

	INSERT INTO CATEGORY (CATEGORY_ID ,IMAGE_LOCATION, CATEGORY_COLUMN , PARENT_ID, SORT_ORDER ,STATUS )VALUES(1,'ASDE',2,3,2,1);
	ALTER TABLE CATEGORY ADD COLUMN CATEGORY_NAME VARCHAR(45);
	ALTER TABLE CATEGORY DROP COLUMN category_column;
	ALTER TABLE CATEGORY ADD COLUMN seo_id bigint;
	ALTER TABLE CATEGORY ADD FOREIGN KEY (seo_id) REFERENCES seo;
	ALTER TABLE CATEGORY ALTER COLUMN PARENT_ID SET DEFAULT 0;
	ALTER TABLE CATEGORY ADD COLUMN description varchar(45);

CREATE TABLE attribute
(
  
attribute_id bigint NOT NULL,
  
category_id bigint NOT NULL,
attribute_name character varying(45),
 
sort_order smallint,
  
CONSTRAINT attribute_pkey PRIMARY KEY (attribute_id),

CONSTRAINT category_id_fkey FOREIGN KEY (category_id)
      REFERENCES category (category_id) MATCH SIMPLE
  
ON UPDATE NO ACTION ON DELETE NO ACTION);
ALTER TABLE attribute DROP COLUMN category_id;
CREATE TABLE banner_group(
banner_group_id bigint NOT NULL,
banner_group_name character varying(100),
banner_size character varying(100),
sort_order integer
);

CREATE TABLE attribute_category
(
  attribute_category_id bigint,
  sub_category_id bigint,
  attribute_id bigint
  CONSTRAINT attribute_category_attribute_id_fkey FOREIGN KEY (attribute_id)
      REFERENCES attribute (attribute_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT attribute_category_category_id_fkey FOREIGN KEY (sub_category_id)
      REFERENCES category (category_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

ALTER TABLE attribute_category
  ADD CONSTRAINT attribute_category_id_pk 
    PRIMARY KEY (attribute_category_id);

CREATE TABLE banner(
banner_id bigint NOT NULL,
banner_name character varying(100),
banner_image character varying(45),
banner_url character varying(100),
sort_order integer,
banner_group_id bigint);
CREATE TABLE COMMISSION (
	COMMISSION_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	TYPE VARCHAR(45),
	VALUE FLOAT,
	SORT_ORDER SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
CREATE TABLE CONTACT_TYPE (
CONTACT_TYPE_ID  SMALLINT PRIMARY KEY NOT NULL,
CONTACT_TYPE  VARCHAR(45)
);
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (1,'MOBILE');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (2,'PHONE');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (3,’E-MAIL’);
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (4,’ALTERNATE  E-MAIL’);
CREATE TABLE CONTACT (CONTACT_ID BIGINT PRIMARY KEY NOT NULL, 
	CONTACT_TYPE VARCHAR(45), 
	CONTACT_VALUE VARCHAR(45),
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP);
ALTER TABLE CONTACT ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW();

ALTER TABLE CONTACT ALTER COLUMN CREATED_DTTM SET DEFAULT NOW();


ALTER TABLE CONTACT RENAME COLUMN CONTACT_TYPE TO CONTACT_TYPE_ID;
CREATE TABLE COURIER (
	COURIER_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	IMAGE VARCHAR(45),
    
	SORT_ORDER SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	ALTER TABLE courier ADD COLUMN courier_name character varying(45);
    ALTER TABLE courier ADD COLUMN estimated_delivery_time time with time zone;
    ALTER TABLE courier DROP COLUMN product_limit small int;
    ALTER TABLE courier ALTER COLUMN estimated_delivery_time TYPE character varying(20);
CREATE TABLE CATEGORY  (
	CATEGORY_ID BIGINT PRIMARY KEY,
	IMAGE_LOCATION VARCHAR(45),
	CATEGORY_COLUMN BIGINT,
	PARENT_ID BIGINT,
	SORT_ORDER SMALLINT,
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);

	INSERT INTO CATEGORY (CATEGORY_ID ,IMAGE_LOCATION, CATEGORY_COLUMN , PARENT_ID, SORT_ORDER ,STATUS )VALUES(1,'ASDE',2,3,2,1);
	ALTER TABLE CATEGORY ADD COLUMN CATEGORY_NAME VARCHAR(45);
	ALTER TABLE CATEGORY DROP COLUMN category_column;
	ALTER TABLE CATEGORY ADD COLUMN seo_id bigint;
	ALTER TABLE CATEGORY ADD FOREIGN KEY (seo_id) REFERENCES seo;
	ALTER TABLE CATEGORY ALTER COLUMN PARENT_ID SET DEFAULT 0;
	ALTER TABLE CATEGORY ADD COLUMN description varchar(45);

CREATE TABLE attribute(attribute_id bigint NOT NULL,
  
category_id bigint NOT NULL,
attribute_name character varying(45),
 
sort_order smallint,
  
CONSTRAINT attribute_pkey PRIMARY KEY (attribute_id),

CONSTRAINT category_id_fkey FOREIGN KEY (category_id)
      REFERENCES category (category_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION);
      
ALTER TABLE attribute DROP COLUMN category_id;
CREATE TABLE banner_group(
banner_group_id bigint NOT NULL,
banner_group_name character varying(100),
banner_size character varying(100),
sort_order integer
);
CREATE TABLE banner(
banner_id bigint NOT NULL,
banner_name character varying(100),
banner_image character varying(45),
banner_url character varying(100),
sort_order integer,
banner_group_id bigint;
);
CREATE TABLE COMMISSION (
	COMMISSION_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	TYPE VARCHAR(45),
	VALUE FLOAT,
	SORT_ORDER SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
CREATE TABLE CONTACT_TYPE (
CONTACT_TYPE_ID  SMALLINT PRIMARY KEY NOT NULL,
CONTACT_TYPE  VARCHAR(45)
);
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (1,'MOBILE');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (2,'PHONE');
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (3,’E-MAIL’);
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (4,’ALTERNATE  E-MAIL’);
CREATE TABLE CONTACT (
	CONTACT_ID BIGINT SERIAL PRIMARY KEY NOT NULL, 
	CONTACT_TYPE VARCHAR(45), 
	CONTACT_VALUE VARCHAR(45),
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP 
);
ALTER TABLE CONTACT ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW();

ALTER TABLE CONTACT ALTER COLUMN CREATED_DTTM SET DEFAULT NOW();


ALTER TABLE CONTACT RENAME COLUMN CONTACT_TYPE TO CONTACT_TYPE_ID;
CREATE TABLE COURIER (
	COURIER_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	IMAGE VARCHAR(45),
    
	SORT_ORDER SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	ALTER TABLE courier ADD COLUMN courier_name character varying(45);
    ALTER TABLE courier ADD COLUMN estimated_delivery_time time with time zone;
    ALTER TABLE courier DROP COLUMN product_limit small int;
    ALTER TABLE courier ALTER COLUMN estimated_delivery_time TYPE character varying(20);

CREATE TABLE CURRENCY (
	CURRENCY_ID BIGINT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(45),
	CODE VARCHAR(45),
	SYMBOL_LEFT CHAR(1),
	SYMBOL_RIGHT CHAR(1),
	DECIMAL_PLACE SMALLINT,
	VALUE FLOAT,
	STATUS VARCHAR(45),	
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
CREATE TABLE CUSTOMER_ADDRESS (
CUSTOMER_ID BIGINT REFERENCES CUSTOMER (CUSTOMER_ID),
ADDRESS_ID BIGINT REFERENCES ADDRESS (ADDRESS_ID)
 );
CREATE TABLE CUSTOMER_CONTACT (
CUSTOMER_ID BIGINT REFERENCES CUSTOMER (CUSTOMER_ID),
CONTACT_ID BIGINT REFERENCES CONTACT (CONTACT_ID)
);
CREATE TABLE SELLER (
	SELLER_ID BIGINT PRIMARY KEY NOT NULL, 
	FIRST_NAME VARCHAR(45)NOT NULL, 
	LAST_NAME VARCHAR(45), 
	GENDER SMALLINT,
	DOB VARCHAR(45),
	TIN_NO VARCHAR(45), 
	COMPANY_NAME VARCHAR(45) NOT NULL, 
	COMPANY_LOGO VARCHAR(45), 
	EPCH_NO VARCHAR(45) NOT NULL, 
	VAT_NO VARCHAR(45) NOT NULL, 
	CST_NO VARCHAR(45) NOT NULL, 
	COMMISSION VARCHAR(45), 
	STATUS SMALLINT, 
	APPROVED SMALLINT, 
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP 
);
ALTER TABLE SELLER ALTER COLUMN GENDER TYPE VARCHAR(45);

ALTER TABLE SELLER ALTER COLUMN GENDER TYPE SMALLINT USING (TRIM(GENDER)::SMALLINT);

ALTER TABLE SELLER ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW();

ALTER TABLE SELLER ALTER COLUMN CREATED_DTTM SET DEFAULT NOW();

ALTER TABLE SELLER ALTER COLUMN EPCH_NO DROP NOT NULL;

ALTER TABLE SELLER ALTER COLUMN VAT_NO DROP NOT NULL;

ALTER TABLE SELLER ALTER COLUMN CST_NO DROP NOT NULL;

ALTER TABLE SELLER ALTER COLUMN COMPANY_NAME DROP NOT NULL;

ALTER TABLE SELLER ADD COLUMN PASSWORD VARCHAR(70);

ALTER TABLE SELLER ADD COLUMN GST_NO VARCHAR(45);

ALTER TABLE SELLER DROP COLUMN COMMISSION;

ALTER TABLE SELLER ADD COLUMN COMMISSION_ID BIGINT REFERENCES COMMISSION(COMMISSION_ID);

 CREATE TABLE CUSTOMER (
	CUSTOMER_ID BIGINT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(45),
	LAST_NAME VARCHAR(45),
	GENDER SMALLINT,
	DOB VARCHAR(45),	
	PASSWORD VARCHAR(45),
	IP VARCHAR(45),
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
CREATE TABLE GEO_ZONE (
	GEO_ZONE_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	DESCRIPTION VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW(),
	SORT_ORDER INTEGER);
	ALTER TABLE GEO_ZONE ADD COLUMN sortorder integer;
CREATE TABLE INFORMATION (
	INFORMATION_ID BIGINT PRIMARY KEY NOT NULL,
        INFORMATION_TITLE CHARACTER VARYING(45),
	DESCRIPTION CHARACTER VARYING(500),
	META_TITLE CHARACTER VARYING(50),
	META_DESCRIPTION CHARACTER VARYING(100),
	META_KEYWORD CHARACTER VARYING(50),
	IS_ACTIVE CHARACTER VARYING(20),
	SORT_ORDER INTEGER
	);
 CREATE TABLE INVOICE (
	INVOICE_ID BIGINT PRIMARY KEY NOT NULL,
	INVOICE_NO VARCHAR(45),
	INVOICE_PREFIX VARCHAR(45),
	CUSTOMER_ID BIGINT REFERENCES CUSTOMER(CUSTOMER_ID),
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID),
	INVOICE_DATE VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()	
	);
CREATE TABLE LENGTH_CLASS (
	LENGTH_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT STRING,
	SORT_ORDER CHARACTER VARYING(20)
	);
	INSERT INTO LENGTH_CLASS(LENGTH_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.5,'PEN',3);
	
	ALTER TABLE LENGTH_CLASS ADD COLUMN SORT_ORDER CHARACTER VARYING(20);
	
	ALTER TABLE LENGTH_CLASS ALTER COLUMN UNIT STRING;
CREATE TABLE order_status
(
  order_status_id bigint NOT NULL,
  order_status_title character varying(45),
  order_status_subject character varying(45),
  description character varying(100),
  sort_order integer
);
CREATE TABLE ATTRIBUTE_GROUP_DESC (
	ATTRIBUTE_GROUP_ID BIGINT PRIMARY KEY NOT NULL,
	ATTRIBUTE_GROUP_NAME VARCHAR(45),
	SORT_ORDER SMALLINT
	);
	
	CREATE TABLE LENGTH_CLASS (
	LENGTH_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT NUMERIC,
	SORT_ORDER CHARACTER VARYING(20)
	);
		INSERT INTO LENGTH_CLASS(LENGTH_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.5,'PEN',3);
	
	ALTER TABLE LENGTH_CLASS ADD COLUMN SORT_ORDER CHARACTER VARYING(20);
	
	
	ALTER TABLE LENGTH_CLASS ALTER COLUMN UNIT STRING;
	
	CREATE TABLE WEIGHT_CLASS (
	WEIGHT_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT NUMERIC
);
CREATE TABLE TAX_CLASS (
	TAX_CLASS_ID BIGINT PRIMARY KEY,
	TITLE VARCHAR(45),
	DESCRIPTION VARCHAR(45), 
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	
		ALTER TABLE TAX_CLASS ADD COLUMN IS_ACTIVE SMALLINT;

	INSERT INTO TAX_CLASS (TAX_CLASS_ID,TITLE,DESCRIPTION) values (1,'VAT','VAT RATE (%)');
	INSERT INTO TAX_CLASS (TAX_CLASS_ID,TITLE,DESCRIPTION) values (1,'CST','CST RATE (%)');
	INSERT INTO TAX_CLASS (TAX_CLASS_ID,TITLE,DESCRIPTION) values (1,'GST','GST RATE (%)');

	
	INSERT INTO WEIGHT_CLASS(WEIGHT_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.3,'ZXCV',3);
	CREATE TABLE product
(
  product_id bigint NOT NULL,
  category_id bigint,
  model character varying(45),
  sku character varying(45),
  upc character varying(45),
  location character varying(45),
  quantity character varying(45),
  stock_status_id character varying(45),
  image character varying(45),
  seller_id bigint,
  shipping bigint,
  price double precision,
  points smallint,
  tax_class_id bigint,
  date_available timestamp without time zone,
  weight character varying(45),
  weight_class_id bigint,
  length numeric,
  width numeric,
  height numeric,
  length_class_id bigint,
  subtract numeric,
  minimum numeric,
  sort_order character varying(45),
  status smallint,
  viewed smallint,
  created_dttm timestamp without time zone DEFAULT now(),
  modified_dttm timestamp without time zone DEFAULT now(),
  CONSTRAINT product_pkey PRIMARY KEY (product_id),
  CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id)
      REFERENCES category (category_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT product_length_class_id_fkey FOREIGN KEY (length_class_id)
      REFERENCES length_class (length_class_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT product_seller_id_fkey FOREIGN KEY (seller_id)
      REFERENCES seller (seller_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT product_tax_class_id_fkey FOREIGN KEY (tax_class_id)
      REFERENCES tax_class (tax_class_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT product_weight_class_id_fkey FOREIGN KEY (weight_class_id)
      REFERENCES weight_class (weight_class_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
 ALTER table product alter column date_available type varchar(45) using date_available::date;
 
 ALTER TABLE PRODUCT DROP COLUMN SELLER_ID;
 
 ALTER TABLE PRODUCT ADD COLUMN PRODUCT_NAME VARCHAR(45);
 
CREATE TABLE PRODUCT_ATTRIBUTE (
	ATTRIBUTE_ID BIGINT PRIMARY KEY NOT NULL,
	ATTRIBUTE_GROUP_ID BIGINT REFERENCES ATTRIBUTE_GROUP_DESC(ATTRIBUTE_GROUP_ID),
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	TEXT VARCHAR(100),
	SORT_ORDER SMALLINT
	);
CREATE TABLE PRODUCT_DESCRIPTION (
	PRODUCT_DESCRIPTION_ID BIGINT PRIMARY KEY,
	PRODUCT_ID BIGINT REFERENCES PRODUCT(PRODUCT_ID),
	NAME VARCHAR(45),
	DESCRIPTION VARCHAR(45),
	META_DESCRIPTION VARCHAR(45),
	META_KEYWORD VARCHAR(45),
	TAG VARCHAR(45)
	);
CREATE TABLE PRODUCT_DISCOUNT (
	PRODUCT_DISCOUNT_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT(PRODUCT_ID),
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID),
	QUANTITY NUMERIC,
	PRICE FLOAT,
	START_DATE VARCHAR(45),
	END_DATE VARCHAR(45)
	);
	ALTER TABLE PRODUCT_DISCOUNT ADD COLUMN discount_code character varying(20);
	ALTER TABLE PRODUCT_DISCOUNT RENAME COLUMN PRICE TO VALUE;
CREATE TABLE PRODUCT_IMAGE (
	PRODUCT_IMAGE_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	IMAGE VARCHAR(45),
	SORT_ORDER VARCHAR(45)
	);
CREATE TABLE PRODUCT_RATING (
PRODUCT_RATING_ID BIGINT PRIMARY KEY NOT NULL,
PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
CUSTOMER_ID BIGINT REFERENCES CUSTOMER (CUSTOMER_ID),
POINTS NUMERIC 
);
CREATE TABLE PRODUCT_REVIEW (
PRODUCT_REVIEW_ID BIGINT PRIMARY KEY NOT NULL,
PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
CUSTOMER_ID BIGINT REFERENCES CUSTOMER (CUSTOMER_ID),
AUTHOUR VARCHAR(45),
TEXT VARCHAR(45),
RATING SMALLINT,
STATUS SMALLINT,
CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
MODIFIED_DTTM TIMESTAMP DEFAULT NOW()	
);

CREATE TABLE SEO( 
	SEO_ID BIGINT PRIMARY KEY NOT NULL,
	META_TITLE VARCHAR(45),
	META_DESC VARCHAR(45),
	META_KEYWORD VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	CREATE TABLE TAX_RATE (
	TAX_RATE_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	SELLER_ID BIGINT REFERENCES SELLER (SELLER_ID),
	NAME VARCHAR(45),
	RATE SMALLINT,
	TYPE VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
 	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	CREATE TABLE TAX_RULE (
	TAX_RULE_ID BIGINT PRIMARY KEY NOT NULL,
	TAX_CLASS_ID BIGINT REFERENCES TAX_CLASS (TAX_CLASS_ID),
	TAX_RATE_ID BIGINT REFERENCES TAX_RATE (TAX_RATE_ID),
	VALUE VARCHAR(5),
	BASED VARCHAR(45),
	PRIORITY SMALLINT
	);
	CREATE TABLE USER_GROUP  (
USER_GROUP_ID BIGINT PRIMARY KEY NOT NULL,
NAME VARCHAR(45),
PERMISSION VARCHAR(45)
)
ALTER TABLE user_group ADD COLUMN group_name character varying(45);
ALTER TABLE user_group ADD COLUMN sort_order integer;
CREATE TABLE STORE (
	STORE_ID BIGINT PRIMARY KEY NOT NULL,
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID),
	NAME VARCHAR(45),
	STORE_URL VARCHAR(45),
	STORE_DESCRIPTION VARCHAR(300),
	RETURN VARCHAR(1000),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
);
CREATE TABLE SELLER_ADDRESS (
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID), 
	ADDRESS_ID BIGINT REFERENCES ADDRESS(ADDRESS_ID) 
	);
	
CREATE TABLE SELLER_CONTACT (
	SELLER_CONTACT_ID BIGINT PRIMARY KEY NOT NULL, 
	SELLER_ID BIGINT REFERENCES CRAFART.SELLER(SELLER_ID), 
	CONTACT_ID BIGINT REFERENCES CONTACT(CONTACT_ID)
);
ALTER TABLE SELLER_CONTACT DROP COLUMN SELLER_CONTACT_ID;
CREATE TABLE SELLER_PRODUCT (
SELLER_ID BIGINT REFERENCES SELLER (SELLER_ID),
PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
SKU VARCHAR(45)
 );
 CREATE TABLE CRAFART_ORDER (
	ORDER_ID BIGINT PRIMARY KEY NOT NULL,
	INVOICE_ID BIGINT REFERENCES INVOICE(INVOICE_ID),
	STORE_ID BIGINT REFERENCES STORE(STORE_ID),
	CUSTOMER_ID BIGINT REFERENCES CUSTOMER(CUSTOMER_ID),
	COURIER_ID BIGINT REFERENCES COURIER(COURIER_ID),
	PRODUCT_ID BIGINT REFERENCES PRODUCT(PRODUCT_ID),
	COMMENT VARCHAR(45),
	TAX_RATE_ID BIGINT REFERENCES TAX_RATE(TAX_RATE_ID),
	TOTAL FLOAT,
	OREDER_STATUS_ID SMALLINT,
	CURRENCY_ID BIGINT REFERENCES CURRENCY(CURRENCY_ID),
	COMMISION_ID BIGINT REFERENCES COMMISSION(COMMISSION_ID),
	ORDER_IP VARCHAR(45),
	FORWARDED_IP VARCHAR(45),
	USER_ID BIGINT REFERENCES CRAFART_USER(USER_ID),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
	CREATE TABLE CRAFART_USER (
	USER_ID BIGINT PRIMARY KEY NOT NULL,
	USER_GROUP_ID BIGINT,
	USER_NAME VARCHAR(45),
	PASSWORD VARCHAR(45),
	FIRST_NAME VARCHAR(45),
	LAST_NAME VARCHAR(45),
	IP VARCHAR(45),
	STATUS SMALLINT,
	SELLER_PERMISSION SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	);
ALTER TABLE CRAFART_USER DROP COLUMN USER_GROUP_ID;
ALTER TABLE crafart_user ADD COLUMN user_group_id bigint;
ALTER TABLE crafart_user ADD FOREIGN KEY (user_group_id) REFERENCES user_group;
CREATE TABLE PRODUCT_SPECIAL (
	PRODUCT_SPECIAL_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	SELLER_ID BIGINT REFERENCES SELLER (SELLER_ID),
	PRICE NUMERIC,
	START_DATE DATE, 
	END_DATE DATE
	);
ALTER TABLE PRODUCT_SPECIAL ALTER COLUMN START_DATE TYPE VARCHAR(45) USING START_DATE::DATE;
	 
ALTER TABLE PRODUCT_SPECIAL ALTER COLUMN END_DATE TYPE VARCHAR(45) USING END_DATE::DATE;

 CREATE TABLE PRODUCT_SHIPPING (
	PRODUCT_SHIPPING_ID BIGINT PRIMARY KEY NOT NULL,
	SHIPPING_RATE FLOAT,
	COURIER_ID BIGINT REFERENCES COURIER(COURIER_ID),
	PRODUCT_ID BIGINT REFERENCES PRODUCT(PRODUCT_ID),
	GEO_ZONE_ID BIGINT REFERENCES GEO_ZONE(GEO_ZONE_ID)
	);
	
CREATE TABLE USER_CONTACT (
USER_CONTACT_ID BIGINT PRIMARY KEY NOT NULL,
USER_ID BIGINT REFERENCES CRAFART_USER (USER_ID),
CONTACT_ID BIGINT REFERENCES CONTACT(CONTACT_ID)
);

CREATE TABLE USER_GROUP  (
USER_GROUP_ID BIGINT PRIMARY KEY NOT NULL,
NAME VARCHAR(45),
PERMISSION VARCHAR(45)
);
ALTER TABLE user_group ADD COLUMN group_name character varying(45);
ALTER TABLE user_group ADD COLUMN sort_order integer;
