/**
 * 
 */
package com.crafart.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Account entity data objects maps to account table in crafart database
 * account_id is primary key which is generated by sequence generator
 * 
 * @author Karthi
 * 
 */
@Entity
@Table(name = "ACCOUNT")
public class AccountDO implements Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5690130471573325342L;

	@Id
	@Column(name = "account_Id")
	@SequenceGenerator(name = "seq_account", sequenceName = "seq_account")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_account")
	private long accountId;

	@Column(name = "bank_Name")
	private String bankName;

	@Column(name = "type")
	private String type;

	@Column(name = "account_Name")
	private String accountName;

	@Column(name = "account_Number")
	private String accountNumber;

	@Column(name = "ifsc_Code")
	private String ifscCode;

	@Column(name = "micr")
	private String micrCode;

	@Column(name = "branch_Name")
	private String branchName;

	public long getAccountId() {
		return accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getIfscCode() {
		return ifscCode;
	}

	public void setIfscCode(String ifscCode) {
		this.ifscCode = ifscCode;
	}

	public String getMicrCode() {
		return micrCode;
	}

	public void setMicrCode(String micrCode) {
		this.micrCode = micrCode;
	}

	public String getBranchName() {
		return branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

}
