/**
 * 
 */
package com.crafart.dataobjects;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * order entity are mapped to crafart_order table in crafart database orderid is
 * primary key which is generated by sequenceGenerator
 * 
 * @author Deepam
 *
 */
@Entity
@Table(name = "CRAFART_ORDER")
public class OrderDO implements Serializable,Cloneable  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7602757957648166911L;
	

	@Id
	@Column(name = "order_Id")
	@SequenceGenerator(name = "seq_order", sequenceName = "seq_order", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_order")
	private long orderId;
	
	@OneToOne
	@JoinColumn(name = "invoice_id", nullable = false)
	private InvoiceDO invoiceDO;
	
	@OneToMany
	@JoinColumn(name = "store_id", nullable = false)
	private StoreDO storeDO;
	
	@OneToOne
	@JoinColumn(name = "customer_id", nullable = false)
	private CustomerDO customerDO;
	
	@OneToMany
	@JoinColumn(name = "courier_id", nullable = false)
	private CourierDO courierDO;
	
	@OneToOne
	@JoinColumn(name = "product_id", nullable = false)
	private ProductDO productDO;
	
	@OneToMany
	@JoinColumn(name = "shipping_address_id", nullable = false)
	private AddressDO addressDO;
	
	
	@OneToOne
	@JoinColumn(name = "billing_address_id", nullable = false)
	private AddressDO addressDo;
	
	@Column(name="comment")
	private String comment;
	
	
	@OneToMany
	@JoinColumn(name = "tax_rate_id", nullable = false)
	private TaxRateDO taxRateDO;
	
	
	@Column(name="total")
	private double total;
	
	

	@Column(name="order_status_id")
	private long orderStatusId;
	
	
	@OneToOne
	@JoinColumn(name = "currency_id", nullable = false)
	private CurrencyDO currencyDO;
	
	@OneToOne
	@JoinColumn(name = "commission_id", nullable = false)
	private CommisionDO commisionDO;
	
	@Column(name="order_ip")
	private String orderIp;
	
	@Column(name="forwarded_ip")
	private String forwardedIp;
	
	@OneToOne
	@JoinColumn(name = "user_id", nullable = false)
	private UserDO userDO;
	
	@Column(name="created_dttm")
	private String createdDttm;
	
	@Column(name="modified_dttm")
	private String modifiedDttm;
	
	public long getOrderId() {
		return orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	
	public InvoiceDO getInvoiceDO() {
		return invoiceDO;
	}

	public void setInvoiceDO(InvoiceDO invoiceDO) {
		this.invoiceDO = invoiceDO;
	}
	
	public StoreDO getStoreDO() {
		return storeDO;
	}

	public void setStoreDO(StoreDO storeDO) {
		this.storeDO = storeDO;
	}
	
	public CustomerDO getCustomerDO() {
		return customerDO;
	}

	public void setCustomerDO(CustomerDO customerDO) {
		this.customerDO = customerDO;
	}
	
	public CourierDO getCourierDO() {
		return courierDO;
	}

	public void setCourierDO(CourierDO courierDO) {
		this.courierDO = courierDO;
	}
	
	public ProductDO getProductDO() {
		return productDO;
	}

	public void setProductDO(ProductDO productDO) {
		this.productDO = productDO;
	}
	
	public AddressDO getAddressDO() {
		return addressDO;
	}

	public void setAdressDO(AddressDO addressDO) {
		this.addressDO = addressDO;
	}
	
	public AddressDO getAddressDo() {
		return addressDo;
	}

	public void setAdressDo(AddressDO addressDo) {
		this.addressDo = addressDo;
	}
	
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment= comment;
	}
	
	public TaxRateDO getTaxRateDO() {
		return taxRateDO;
	}

	public void setTaxRateDO(TaxRateDO taxRateDO) {
		this.taxRateDO = taxRateDO;
	}

	 
	public Double getTotal() {
		return total;
	}

	public void setTotal(Double total) {
		this.total= total;
	}
	
	public long getOrderStatusId() {
		return orderStatusId;
	}

	public void setOrderStatusId(long orderStatusId) {
		this.orderStatusId= orderStatusId;
	}
	
	public CurrencyDO getCurrencyDO() {
		return currencyDO;
	}

	public void setCurrencyDO(CurrencyDO currencyDO) {
		this.currencyDO = currencyDO;
	}
	
	public CommisionDO getCommisionDO() {
		return commisionDO;
	}

	public void setCommisionDO(CommisionDO commisionDO) {
		this.commisionDO = commisionDO;
	}
	
	public String getOrderIp() {
		return orderIp;
	}

	public void setOrderIp(String orderIp) {
		this.orderIp= orderIp;
	}

	public String getForwardedIp() {
		return forwardedIp;
	}

	public void setForwardedIp(String forwardedIp) {
		this.forwardedIp= forwardedIp;
	}
	
	public UserDO getUserDO() {
		return userDO;
	}

	public void setUserDO(UserDO userDO) {
		this.userDO = userDO;
	}
	
	
	public String getCreatedDttm() {
		return createdDttm;
	}

	public void setCreatedDttm(String createdDttm) {
		this.createdDttm= createdDttm;
	}

	
	public String getModifiedDttm() {
		return modifiedDttm;
	}

	public void setModifiedDttm(String modifiedDttm) {
		this.modifiedDttm= modifiedDttm;
	}
}





	
	
	
	
	
	




	


