/**
 * 
 */
package com.crafart.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * seller entity data object maps to seller table in crafart database. Property
 * belongs to seller table and seller_id is primary key which is generated by db
 * sequence <blockquote>seq_seller<blockquote>
 * 
 * @author karthi
 * @version 1.0
 */
@Entity
@Table(name = "SELLER")
public class SellerDO implements Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8925439571526520112L;

	@Id
	@Column(name = "seller_Id")
	@SequenceGenerator(name = "seller_seq", sequenceName = "seller_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seller_seq")
	private long sellerId;

	private String first_Name;

	private String last_Name;

	private int tin_no;

	private String company_Name;

	private String company_Logo;

	private String epch_no;

	private String vat_no;

	private String cst_no;

	private String commission;

	private int status;

	private int approved;

	public long getSellerId() {
		return sellerId;
	}

	public void setSellerId(long sellerId) {
		this.sellerId = sellerId;
	}

	public String getFirstName() {
		return first_Name;
	}

	public void setFirstName(String firstName) {
		this.first_Name = firstName;
	}

	public String getLastName() {
		return last_Name;
	}

	public void setLastName(String lastName) {
		this.last_Name = lastName;
	}

	public int getTin_no() {
		return tin_no;
	}

	public void setTin_no(int tin_no) {
		this.tin_no = tin_no;
	}

	public String getCompanyName() {
		return company_Name;
	}

	public void setCompanyName(String companyName) {
		this.company_Name = companyName;
	}

	public String getCompanyLogo() {
		return company_Logo;
	}

	public void setCompanyLogo(String companyLogo) {
		this.company_Logo = companyLogo;
	}

	public String getEpch_no() {
		return epch_no;
	}

	public void setEpch_no(String epch_no) {
		this.epch_no = epch_no;
	}

	public String getVat_no() {
		return vat_no;
	}

	public void setVat_no(String vat_no) {
		this.vat_no = vat_no;
	}

	public String getCst_no() {
		return cst_no;
	}

	public void setCst_no(String cst_no) {
		this.cst_no = cst_no;
	}

	public String getCommission() {
		return commission;
	}

	public void setCommission(String commission) {
		this.commission = commission;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getApproved() {
		return approved;
	}

	public void setApproved(int approved) {
		this.approved = approved;
	}

}
