/**
 * 
 */
package com.crafart.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * store entity data object maps to store table in crafart database. Property
 * belongs to store table and store_id is primary key which is generated by db
 * sequence <blockquote>seq_store<blockquote>
 * 
 * @author Karthi
 * @version 1.0
 * 
 */
@Entity
@Table(name = "STORE")
public class StoreDO implements Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3168290124126749175L;

	@Id
	@Column(name = "store_id")
	@SequenceGenerator(name = "seq_store", sequenceName = "seq_store")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_store")
	private long storeId;

	@Column(name = "seller_id")
	private long sellerId;

	@Column(name = "name")
	private String name;

	@Column(name = "store_url")
	private String storeUrl;

	@Column(name = "store_description")
	private String store_Description;

	@Column(name = "return")
	private String store_Return;

	public long getStoreId() {
		return storeId;
	}

	public void setStoreId(long storeId) {
		this.storeId = storeId;
	}

	public long getSellerId() {
		return sellerId;
	}

	public void setSellerId(long sellerId) {
		this.sellerId = sellerId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStoreUrl() {
		return storeUrl;
	}

	public void setStoreUrl(String storeUrl) {
		this.storeUrl = storeUrl;
	}

	public String getStore_Description() {
		return store_Description;
	}

	public void setStore_Description(String store_Description) {
		this.store_Description = store_Description;
	}

	public String getStore_Return() {
		return store_Return;
	}

	public void setStore_Return(String store_Return) {
		this.store_Return = store_Return;
	}

}
