/**
 * 
 */
package com.crafart.data;

import org.apache.log4j.Logger;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.crafart.dataobjects.ProductDO;
import com.crafart.exception.CrafartDataException;

/**
 * @author Karthi
 * @version 1.0
 * 
 */
@Repository("ProductDAOImpl")
public class ProductDAOImpl implements ProductDAO {

	@SuppressWarnings("unused")
	private static final Logger log = Logger.getLogger(ProductDAOImpl.class);

	private SessionFactory sessionFactory;

	@Autowired
	public void setSessionFactory(SessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}

	/**
	 * adding product details to product table productId is generated by seq
	 * automatically
	 * 
	 */

	@Override
	public int addProduct(ProductDO productDO) throws CrafartDataException {
		try {
			Session session = this.sessionFactory.openSession();
			Transaction transaction = session.beginTransaction();
			session.persist(productDO);
			transaction.commit();
			session.close();
		} catch (HibernateException hExp) {
			throw new CrafartDataException("Error while adding product ", hExp);
		}
		return 0;
	}

}
