CREATE TABLE ACCOUNT (
	ACCOUNT_ID BIGINT PRIMARY KEY NOT NULL, 
	BANK_NAME VARCHAR(45), 
	TYPE VARCHAR(45), 
	ACCOUNT_NAME VARCHAR(45), 
	ACCOUNT_NUMBER VARCHAR(45), 
	IFSC_CODE VARCHAR(45), 
	MICR VARCHAR(45), 
	BRANCH_NAME VARCHAR(45), 
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
