CREATE TABLE ADDRESS (
	ADDRESS_ID BIGINT SERIAL PRIMARY KEY NOT NULL, 
	STREET VARCHAR(45), 
	STATE_ID BIGINT, 
	CITY_ID BIGINT, 
	PIN_CODE VARCHAR(45), 
	CREATED_DTTM TIMESTAMP,
	MODIFIED_DTTM TIMESTAMP
)