CREATE TABLE CATEGORY  (
	CATEGORY_ID BIGINT PRIMARY KEY,
	IMAGE_LOCATION VARCHAR(45),
	CATEGORY_COLUMN BIGINT,
	PARENT_ID BIGINT,
	SORT_ORDER SMALLINT,
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
	
/**CATEGORY_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO CATEGORY (CATEGORY_ID ,IMAGE_LOCATION, CATEGORY_COLUMN , PARENT_ID, STOCK_ORDER ,STATUS )VALUES(1,'ASDE',2,3,2,1)
	