CREATE TABLE CATEGORY  (
	CATEGORY_ID BIGINT PRIMARY KEY,
	IMAGE_LOCATION VARCHAR(45),
	CATEGORY_COLUMN BIGINT,
	PARENT_ID BIGINT,
	SORT_ORDER SMALLINT,
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)