CREATE TABLE CATEGORY  (
	CATEGORY_ID BIGINT PRIMARY KEY,
	IMAGE_LOCATION VARCHAR(45),
	CATEGORY_COLUMN BIGINT,
	PARENT_ID BIGINT,
	SORT_ORDER SMALLINT,
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
	
/**CATEGORY_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO CATEGORY (CATEGORY_ID ,IMAGE_LOCATION, CATEGORY_COLUMN , PARENT_ID, SORT_ORDER ,STATUS )VALUES(1,'ASDE',2,3,2,1)
	/**
	 * 30-03-2015
	 **/
	ALTER TABLE CATEGORY ADD COLUMN CATEGORY_NAME VARCHAR(45)
	
	/** Alter query added on 04/06/2015 **/
	ALTER TABLE CATEGORY DROP COLUMN category_column
	ALTER TABLE CATEGORY ADD COLUMN seo_id bigint
	ALTER TABLE CATEGORY ADD FOREIGN KEY (seo_id) REFERENCES seo
	ALTER TABLE CATEGORY ALTER COLUMN PARENT_ID SET DEFAULT 0
	ALTER TABLE CATEGORY ADD COLUMN description varchar(45)
	