CREATE TABLE crafart.CONTACT (
	CONTACT_ID BIGINT SERIAL PRIMARY KEY NOT NULL, 
	CONTACT_TYPE VARCHAR(45), 
	CONTACT_VALUE VARCHAR(45),
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP 
)

/**SETTING DEFAULT VALUES TO COLUMN**/ 
ALTER TABLE CONTACT ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW()

ALTER TABLE CONTACT ALTER COLUMN CREATED_DTTM SET DEFAULT NOW()

/*alter query*/
ALTER TABLE CONTACT RENAME COLUMN CONTACT_TYPE TO CONTACT_TYPE_ID;