CREATE TABLE CONTACT_TYPE (
CONTACT_TYPE_ID  SMALLINT PRIMARY KEY NOT NULL,
CONTACT_TYPE  VARCHAR(45)
)

/** INSERT QUERY - THIS IS STATIC TABLE **/

INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (1,'MOBILE')
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (2,'PHONE')
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (3,’E-MAIL’)
INSERT INTO CONTACT_TYPE (CONTACT_TYPE_ID,CONTACT_TYPE) VALUES (4,’ALTERNATE  E-MAIL’)
