CREATE TABLE COURIER (
	COURIER_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	IMAGE VARCHAR(45),
	PRODUCT_LIMIT SMALLINT,
	SORT_ORDER SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)