/** ORDER IN WHICH TABLES HAS TO CREATED.
 * 
 * FOR PRODUCT TABLE
 * 1)CATEGORY TABLE
 * 2)SELLER TABLE
 * 3)TAX_CLASS
 * 4)WEIGHT_CLASS
 * 5)LENGTH_CLASS
 * AFTER CREATING ABOVE TABLES 
 * CREATE PRODUCT TABLE
 * 
 * 
 * 
 **/
