CREATE TABLE CRAFART_ORDER (
	ORDER_ID BIGINT PRIMARY KEY NOT NULL,
	INVOICE_ID BIGINT REFERENCES INVOICE(INVOICE_ID),
	STORE_ID BIGINT REFERENCES STORE(STORE_ID),
	CUSTOMER_ID BIGINT REFERENCES CUSTOMER(CUSTOMER_ID),
	COURIER_ID BIGINT REFERENCES COURIER(COURIER_ID),
	PRODUCT_ID BIGINT REFERENCES PRODUCT_ID(PRODUCT_ID),
	COMMENT VARCHAR(45),
	TAX_RATE_ID BIGINT REFERENCES TAX_RATE(TAX_RATE_ID),
	TOTAL FLOAT,
	OREDER_STATUS_ID SMALLINT,
	CURRENCY_ID BIGINT REFERENCES CURRENCY(CURRENCY_ID),
	COMMISION_ID BIGINT REFERENCES COMMISSION(COMMISSION_ID),
	ORDER_IP VARCHAR(45),
	FORWARDED_IP VARCHAR(45),
	USER_ID BIGINT REFERENCES CRAFART_USER(USER_ID),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)