CREATE TABLE CURRENCY (
	CURRENCY_ID BIGINT PRIMARY KEY NOT NULL,
	TITLE VARCHAR(45),
	CODE VARCHAR(45),
	SYMBOL_LEFT CHAR(1),
	SYMBOL_RIGHT CHAR(1),
	DECIMAL_PLACE SMALLINT,
	VALUE FLOAT,
	STATUS VARCHAR(45),	
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)