 CREATE TABLE CUSTOMER (
	CUSTOMER_ID BIGINT PRIMARY KEY NOT NULL,
	FIRST_NAME VARCHAR(45),
	LAST_NAME VARCHAR(45),
	GENDER SMALLINT,
	DOB VARCHAR(45),	
	PASSWORD VARCHAR(45),
	IP VARCHAR(45),
	STATUS SMALLINT,
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
