CREATE TABLE GEO_ZONE (
	GEO_ZONE_ID BIGINT PRIMARY KEY NOT NULL,
	NAME VARCHAR(45),
	DESCRIPTION VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW(),
	SORT_ORDER INTEGER
	)
	
	
	\**********   ALTER TABLE TO ADD SORTODER **********/
	
	ALTER TABLE GEO_ZONE ADD COLUMN sortorder integer