CREATE TABLE INFORMATION (
	INFORMATION_ID BIGINT PRIMARY KEY NOT NULL,
        INFORMATION_TITLE CHARACTER VARYING(45),
	DESCRIPTION CHARACTER VARYING(500),
	META_TITLE CHARACTER VARYING(50),
	META_DESCRIPTION CHARACTER VARYING(100),
	META_KEYWORD CHARACTER VARYING(50),
	IS_ACTIVE CHARACTER VARYING(20),
	SORT_ORDER INTEGER
	)