 CREATE TABLE INVOICE (
	INVOICE_ID BIGINT PRIMARY KEY NOT NULL,
	INVOICE_NO VARCHAR(45),
	INVOICE_PREFIX VARCHAR(45),
	CUSTOMER_ID BIGINT REFERENCES CUSTOMER(CUSTOMER_ID),
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID),
	INVOICE_DATE VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()	
	)