CREATE TABLE LENGTH_CLASS (
	LENGTH_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT STRING,
	SORT_ORDER CHARACTER VARYING(20)
	)
	
/**LENGTH_CLASS_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO LENGTH_CLASS(LENGTH_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.5,'PEN',3)
	
	/************ ALTER TABLE TO ADD COLUMN SORT_ORDER ************/
	
	ALTER TABLE LENGTH_CLASS ADD COLUMN SORT_ORDER type CHARACTER VARYING(20)
	
	ALTER TABLE LENGTH_CLASS ADD COLUMN IS_ACTIVE int;
	
	/********* ALTERTABLE TO CHANGE UNIT NUMERIC TO UNIT STRING  *************/
	
	ALTER TABLE LENGTH_CLASS ALTER COLUMN UNIT type  character varying(20)