CREATE TABLE LENGTH_CLASS (
	LENGTH_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT NUMERIC
	)
	
/**LENGTH_CLASS_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO LENGTH_CLASS(LENGTH_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.5,'PEN',3)