 CREATE TABLE PRODUCT_SHIPPING (
	PRODUCT_SHIPPING_ID BIGINT PRIMARY KEY NOT NULL,
	SHIPPING_RATE FLOAT,
	COURIER_ID BIGINT REFERENCES COURIER(COURIER_ID),
	PRODUCT_ID BIGINT REFERENCES PRODUCT(PRODUCT_ID),
	GEO_ZONE_ID BIGINT REFERENCES GEO_ZONE(GEO_ZONE_ID)
	)