CREATE TABLE PRODUCT_SPECIAL (
	PRODUCT_SPECIAL_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	SELLER_ID BIGINT REFERENCES SELLER (SELLER_ID),
	PRICE NUMERIC,
	START_DATE DATE, 
	END_DATE DATE
	)
	
	/****01/04/2015 ALTER QUERY******/
	
	 ALTER TABLE PRODUCT_SPECIAL ALTER COLUMN START_DATE TYPE VARCHAR(45) USING START_DATE::DATE
	 
	 ALTER TABLE PRODUCT_SPECIAL ALTER COLUMN END_DATE TYPE VARCHAR(45) USING END_DATE::DATE