/*Added on 05/05/2015 */
CREATE TABLE PRODUCT_REVIEW (
PRODUCT_REVIEW_ID BIGINT PRIMARY KEY NOT NULL,
PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
CUSTOMER_ID BIGINT REFERENCES CUSTOMER (CUSTOMER_ID),
AUTHOUR VARCHAR(45),
TEXT VARCHAR(45),
RATING SMALLINT,
STATUS SMALLINT,
CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
MODIFIED_DTTM TIMESTAMP DEFAULT NOW()	
)
