CREATE TABLE PRODUCT_SPECIAL (
	PRODUCT_SPECIAL_ID BIGINT PRIMARY KEY NOT NULL,
	PRODUCT_ID BIGINT REFERENCES PRODUCT (PRODUCT_ID),
	SELLER_ID BIGINT REFERENCES SELLER (SELLER_ID),
	PRICE NUMERIC,
	START_DATE DATE, 
	END_DATE DATE
	)