CREATE TABLE CRAFART.SELLER_CONTACT (
	SELLER_CONTACT_ID BIGINT SERIAL PRIMARY KEY NOT NULL, 
	SELLER_ID BIGINT REFERENCES CRAFART.SELLER(SELLER_ID), 
	CONTACT_ID BIGINT REFERENCES CRAFART.CONTACT(CONTACT_ID)
)

/*****22/04/2015****/
--		ALTER QUERY

ALTER TABLE SELLER_CONTACT DROP COLUMN SELLER_CONTACT_ID