CREATE TABLE crafart.SELLER (
	SELLER_ID BIGINT SERIAL PRIMARY KEY NOT NULL, 
	FIRST_NAME VARCHAR(45)NOT NULL, 
	LAST_NAME VARCHAR(45), 
	GENDER SMALLINT,
	DOB VARCHAR(45),
	TIN_NO VARCHAR(45), 
	COMPANY_NAME VARCHAR(45) NOT NULL, 
	COMPANY_LOGO VARCHAR(45), 
	EPCH_NO VARCHAR(45) NOT NULL, 
	VAT_NO VARCHAR(45) NOT NULL, 
	CST_NO VARCHAR(45) NOT NULL, 
	COMMISSION VARCHAR(45), 
	STATUS SMALLINT, 
	APPROVED SMALLINT, 
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP 
)
/**changing column type from smallint to varchar**/
ALTER TABLE SELLER ALTER COLUMN GENDER TYPE VARCHAR(45)

/**changing column type from varchar to smallint
 * change all varchar to integer ie from male to some 1 or 0
 */
ALTER TABLE SELLER ALTER COLUMN GENDER TYPE SMALLINT USING (TRIM(GENDER)::SMALLINT)

ALTER TABLE SELLER ALTER COLUMN MODIFIED_DTTM SET DEFAULT NOW()

ALTER TABLE SELLER ALTER COLUMN CREATED_DTTM SET DEFAULT NOW()

ALTER TABLE SELLER ALTER COLUMN EPCH_NO DROP NOT NULL

ALTER TABLE SELLER ALTER COLUMN VAT_NO DROP NOT NULL

ALTER TABLE SELLER ALTER COLUMN CST_NO DROP NOT NULL

ALTER TABLE SELLER ALTER COLUMN COMPANY_NAME DROP NOT NULL

/**Alter query made for seller reg on 22/04/2015**/

ALTER TABLE SELLER ADD COLUMN PASSWORD VARCHAR(70)

/**Alter query made for seller reg on 01/02/2015**/

ALTER TABLE SELLER ADD COLUMN GST_NO VARCHAR(45)

ALTER TABLE SELLER DROP COLUMN COMMISSION 

ALTER TABLE SELLER ADD COLUMN COMMISSION_ID BIGINT REFERENCES COMMISSION(COMMISSION_ID)

