
CREATE TABLE SELLER (
	SELLER_ID BIGINT PRIMARY KEY NOT NULL, 
	FIRST_NAME VARCHAR(45)NOT NULL, 
	LAST_NAME VARCHAR(45), 
	GENDER SMALLINT,
	DOB VARCHAR(45),
	TIN_NO VARCHAR(45), 
	COMPANY_NAME VARCHAR(45) NOT NULL, 
	COMPANY_LOGO VARCHAR(45), 
	EPCH_NO VARCHAR(45) NOT NULL, 
	VAT_NO VARCHAR(45) NOT NULL, 
	CST_NO VARCHAR(45) NOT NULL, 
	COMMISSION VARCHAR(45), 
	STATUS SMALLINT, 
	APPROVED SMALLINT, 
	CREATED_DTTM TIMESTAMP, 
	MODIFIED_DTTM TIMESTAMP 
	)