/** CRRATED ON 04/06/2015 **/

CREATE TABLE SEO( 
	SEO_ID BIGINT PRIMARY KEY NOT NULL,
	META_TITLE VARCHAR(45),
	META_DESC VARCHAR(45),
	META_KEYWORD VARCHAR(45),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
