CREATE TABLE STORE (
	STORE_ID BIGINT PRIMARY KEY NOT NULL,
	SELLER_ID BIGINT REFERENCES SELLER(SELLER_ID),
	NAME VARCHAR(45),
	STORE_URL VARCHAR(45),
	STORE_DESCRIPTION VARCHAR(300),
	RETURN VARCHAR(1000),
	CREATED_DTTM TIMESTAMP DEFAULT NOW(), 
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
)
