CREATE TABLE TAX_CLASS (
	TAX_CLASS_ID BIGINT PRIMARY KEY,
	TITLE VARCHAR(45),
	DESCRIPTION VARCHAR(45), 
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
	
/**TAX_CLASS_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO TAX_CLASS(TAX_CLASS_ID, TITLE, DESCRIPTION)VALUES(1,'ASDFGHJKL','QWERTYUIOP')