CREATE TABLE TAX_CLASS (
	TAX_CLASS_ID BIGINT PRIMARY KEY,
	TITLE VARCHAR(45),
	DESCRIPTION VARCHAR(45), 
	CREATED_DTTM TIMESTAMP DEFAULT NOW(),
	MODIFIED_DTTM TIMESTAMP DEFAULT NOW()
	)
	
	/**** 02/04/2015 	ALTER QUERY ******/
	ALTER TABLE TAX_CLASS ADD COLUMN IS_ACTIVE SMALLINT
	
/**TAX_CLASS_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * 
 **/
