CREATE TABLE TAX_RULE (
	TAX_RULE_ID BIGINT PRIMARY KEY NOT NULL,
	TAX_CLASS_ID BIGINT REFERENCES TAX_CLASS (TAX_CLASS_ID),
	TAX_RATE_ID BIGINT REFERENCES TAX_RATE (TAX_RATE_ID),
	VALUE VARCHAR(5),
	BASED VARCHAR(45),
	PRIORITY SMALLINT
	)