/*
 * Added on 27/05/2015
 */
CREATE TABLE USER_CONTACT (
USER_CONTACT_ID BIGINT PRIMARY KEY NOT NULL,
USER_ID BIGINT REFERENCES CRAFART_USER (USER_ID),
CONTACT_ID BIGINT REFERENCES CONTACT(CONTACT_ID)
)
