CREATE TABLE WEIGHT_CLASS (
	WEIGHT_CLASS_ID BIGINT PRIMARY KEY,
	VALUE FLOAT,
	TITLE VARCHAR(45),
	UNIT NUMERIC
)

/**WEIGHT_CLASS_ID IS USED AS FOREGIN KEY IN PRODUCT TABLE SO FOR TEST INSERT HAS BEEN HARD CODED INSERT QUERY
 * ONLY FOR TESTING
 * **/
	INSERT INTO WEIGHT_CLASS(WEIGHT_CLASS_ID, VALUE, TITLE, UNIT)VALUES(1,2.3,'ZXCV',3)