delete from product_attribute
delete from product_description
delete from product_discount
delete from product_image
delete from product_rating
delete from product_review
delete from product_shipping
delete from crafart_order
delete from tax_rule
delete from tax_rate
delete from seller_product
delete from product